# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9a5b03f48fd2c937c8f0e13f6e0b0fe8650079305ce38bb2aea6989eaf847d2ef76364050370df1c97cd9c6cd8faf73a93790c12db60629f4dac1d3bc5cd864

test:
  secret_key_base: 70282b523cf545e3ba5d07fa17bc172e63b0becfa873659d111afe924989937bacae0e0be91efaa83d1539694716c9114f0ef31d3960f86659f2bd98e046c497

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
